apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-quota
  namespace: nginx-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    pods: "10"
    services: "5"
    replicationcontrollers: "5"
